superhumans:
    humantorch:
        display-name: "The Human Torch"
        equip-phrase: "Flame on"
        potion-effects:
            - INCREASE_DAMAGE:5
            - HEALTH_BOOST:9
            - MINING:3
            - SPEED:3
            - JUMP:3
            - REGENERATION:1
        items:
            fireball:
                material: FIREBALL
                amount: 1
                display-name: "Fireball"
            supernova:
                material: FLINT_AND_STEEL
                amount: 1
                display-name: "Super Nova"
    captainamerica:
        display-name: "&4C&9apt&fain &4A&9mer&4ica"
        equip-phrase: "&4Those who deny freedom to others deserve it not for themselves."
        potion-effects:
            - INCREASE_DAMAGE:5
            - HEALTH_BOOST:4
        items:
            shield:
                material: SHIELD
                amount: 1
                display-name: "&4C&9apt&fain &4A&9mer&4ica's &9Shield"
                enchantments:
                   - DURABILITY:3
                   - MENDING:1
                shield-meta:
                   base-color: ORANGE
                   patterns:
                    - HALF_HORIZONTAL_MIRROR:RED
                    - HALF_HORIZONTAL_MIRROR:RED
                    - CROSS:BLUE
                    - STRIPE_CENTER:BLUE
                    - STRIPE_MIDDLE:BLUE
                    - FLOWER:WHITE
    superman:
        display-name: "&cS&9u&ep&9erm&can"
        equip-phrase: "I'm better than Goku"
        potion-effects:
            - INCREASE_DAMAGE:20
            - REGENERATION:1
            - DAMAGE_RESISTANCE:3
            - FIRE_RESISTANCE:1
            - WATER_BREATHING:1
            - NIGHT_VISION:1
            - HEALTH_BOOST:19
        items:
            laservision:
                material: IRON_BARDING
                amount: 1
                display-name: "&4Kryptonian Laser Vision"
            speedsterboots:
                material: IRON_BOOTS
                amount: 1
                display-name: "&4S&ep&4e&ce&ed&8s&0t&9e&1r &4Boots"
                enchantments:
                  - FROST_WALKER:1
    theflash:
        display-name: "The Flash (Barry Allen)"
        equip-phrase: "I'm Barry Allen"
        potion-effects:
            - INCREASE_DAMAGE:3
            - HEALTH_BOOST:4
            - REGENERATION:1
            - SPEED:0
        items:
            speedforceboots:
                material: IRON_BOOTS
                amount: 1
                display-name: "Speed Force Boots"
            speedmodifier:
                material: FIREWORK_CHARGE
                amount: 1
                display-name: "Speed Modifier"